# Generated by Django 5.0.2 on 2024-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='YxR3tBAibppt', max_length=10, verbose_name='Password'),
        ),
    ]
