# Generated by Django 5.0.2 on 2024-02-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_student_user_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('accno', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('callno', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year_of_published', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=12, unique=True)),
                ('publisher', models.CharField(max_length=50)),
                ('pages', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('available_books', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='kjlpQVfx8LVC', max_length=10, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_id', models.CharField(max_length=10, unique=True)),
                ('accno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
            ],
        ),
    ]
