# Generated by Django 5.0.2 on 2024-02-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_book_alter_student_password_bookcopy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='i5NVsWkzXPm0', max_length=10, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email id')),
                ('password', models.CharField(default='5Z0uIKruqYEm', max_length=10, verbose_name='Password')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
