# Generated by Django 5.0.2 on 2024-02-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_alter_staff_password_alter_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='5YPXAEpT8B21', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='W573zQ4LuOsG', max_length=10, verbose_name='Password'),
        ),
    ]
