# Generated by Django 5.0.2 on 2024-02-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_alter_staff_password_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='accno',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='edition',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='publisher',
            field=models.CharField(default='Unknown Publisher', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='6cYuxmYp7S3S', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='0q5I5Cm8eziz', max_length=10, verbose_name='Password'),
        ),
    ]
