# Generated by Django 5.0.2 on 2024-02-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_remove_bookcopy_accno_bookcopy_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='ZdPMBU6qGcZ6', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='1uB3AFzsDlIF', max_length=10, verbose_name='Password'),
        ),
    ]
