# Generated by Django 5.0.2 on 2024-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_student_user_alter_staff_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='PC3PMoCgx2XF', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='vCjNHqVgvjOz', max_length=10, verbose_name='Password'),
        ),
    ]
