# Generated by Django 5.0.2 on 2024-02-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_alter_staff_password_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='YAvx7cye8aub', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='ZDeD51RNM9EK', max_length=10, verbose_name='Password'),
        ),
    ]
