# Generated by Django 5.0.2 on 2024-02-22 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_alter_staff_password_alter_student_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='GuS2muWamLXm', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='y256Qp61cSQn', max_length=10, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='staff',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='des_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.designation'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=50, unique=True)),
                ('d_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='p_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.program'),
        ),
    ]
