# Generated by Django 5.0.2 on 2024-02-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0020_alter_staff_password_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='no_of_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='NwhpLAg9v1Wy', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='nt6YCe9wy3Qr', max_length=10, verbose_name='Password'),
        ),
    ]
