# Generated by Django 5.0.2 on 2024-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0023_alter_staff_password_alter_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='yMRNdTYnQ0UU', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='qKjlH8Rab8j8', max_length=10, verbose_name='Password'),
        ),
    ]
