# Generated by Django 5.0.2 on 2024-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0025_remove_returnedbook_book_returnedbook_borrowed_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='tdrNeFyXKGFi', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='9QZID9FMcYZp', max_length=10, verbose_name='Password'),
        ),
    ]
